//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTilausDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tuotteet
    {
        public int TuoteID { get; set; }
        public string Nimi { get; set; }
        public decimal Ahinta { get; set; }
        public string KuvaLinkki { get; set; }
    }
}
